dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.9.3

compiler:
  solc:
    version: 0.8.20
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.9.3"

networks:
  default: ganache_gui
  ganache_gui:
    host: 172.29.240.1
    port: 8545
    network_id: 1337  
    gas_limit: auto
    gas_price: 2auto
    max_fee: null
    priority_fee: null